version: 0.2

phases:
  pre_build:
    commands:
      - sudo yum install -y yum-utils shadow-utils tar jq
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin latest
      - cd Main_infra
      - mkdir Output/
      - echo ----------------aws creds----------------
      - aws sts get-caller-identity
      - echo ----------------checking terraform version----------------
      - terraform --version
      - echo ----------------checking trivy version----------------
      - trivy --version
      - |
        if [ "$TF_ITEM" = "scan" ]; then
          echo ----------------Doing Trivy Security scan---------------
          trivy config --exit-code 1 --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL ./
        fi
      - echo ----------------Fetching account list from SSM----------------
      - ACCOUNTS_JSON=$(aws ssm get-parameter --name "/ACCOUNTS" --with-decryption --query "Parameter.Value" --output text)
      - echo "Accounts from SSM - $ACCOUNTS_JSON"
      - ACCOUNTS=$(echo $ACCOUNTS_JSON | tr ',' ' ')
      - echo "Accounts seperate from SSM - $ACCOUNTS"
      - |
        for ACCOUNT_ID in $ACCOUNTS; do
          echo "Assumed role into $ACCOUNT_ID"
          aws sts get-caller-identity
        done
    
  build:
    commands:
      - |
        if [ "$TF_ITEM" = "plan" ]; then
          echo ----------------checking terraform init----------------
          terraform init
          echo ----------------Doing Terraform plan---------------------
          terraform plan
        elif [ "$TF_ITEM" = "apply" ]; then
          echo ----------------checking terraform init----------------
          terraform init
          echo ----------------Doing 1st Terraform apply----------------
          terraform apply --auto-approve
          echo ----------------Doing 2nd terraform apply----------------
          terraform apply --auto-approve
        fi
    
  post_build:
    commands:
      - |
        if [ "$TF_ITEM" = "scan" ]; then
          echo ----------------terraform Trevy Scan completed on `date`------------
          touch Output/$TF_ITEM-file-ItIsEmpty
        elif [ "$TF_ITEM" = "plan" ]; then
          echo ----------------terraform plan completed on `date`------------------
          touch Output/$TF_ITEM-file-ItIsEmpty
        elif [ "$TF_ITEM" = "apply" ]; then
          echo ----------------terraform apply completed on `date`-----------------
          touch Output/$TF_ITEM-file-ThisFileIsEmpty
        fi

artifacts:
  files:
    - 'Main_infra/Output/*'
     