version: 0.2

phases:
  pre_build:
    commands:
      - sudo yum install -y yum-utils shadow-utils tar jq
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin latest
      - cd Main_infra
      - mkdir Output/
      - echo ----------------aws creds----------------
      - aws sts get-caller-identity
      - echo ----------------checking terraform version----------------
      - terraform --version
      - echo ----------------checking trivy version----------------
      - trivy --version
      - |
        if [ "$TF_ITEM" = "scan" ]; then
          echo ----------------Doing Trivy Security scan---------------
          trivy config --exit-code 1 --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL ./
          echo ----------------terraform Trevy Scan completed on `date`------------
          touch Output/$TF_ITEM-file-ItIsEmpty
        fi
      - echo ----------------Fetching account list from SSM----------------
      - ACCOUNTS_JSON=$(aws ssm get-parameter --name "/ACCOUNTS" --with-decryption --query "Parameter.Value" --output text)
      - echo "Accounts from SSM - $ACCOUNTS_JSON"
      - ACCOUNTS=$(echo $ACCOUNTS_JSON | tr ',' ' ')
      - echo "Accounts seperate from SSM - $ACCOUNTS"
    
  build:
    commands:
      - |
        for ACCOUNT_ID in $ACCOUNTS; do
          echo "=============================================================="
          echo "Running Terraform for account: $ACCOUNT_ID"
          echo "=============================================================="
          if [ "$TF_ITEM" = "plan" ]; then
            echo ----------------checking terraform init----------------
            terraform init -reconfigure -backend-config="bucket=codepipeline-bucket-satish-terraform" -backend-config="key=statefolder/$ACCOUNT_ID/terraform.tfstate" -backend-config="region=ap-south-1"
            echo ----------------Doing Terraform plan---------------------
            terraform plan -var="account_id=$ACCOUNT_ID"
            echo ----------------terraform plan completed on `date`------------------
            touch Output/plan-$ACCOUNT_ID-done
          elif [ "$TF_ITEM" = "apply" ]; then
            echo ----------------checking terraform init----------------
            terraform init -reconfigure -backend-config="bucket=codepipeline-bucket-satish-terraform" -backend-config="key=statefolder/$ACCOUNT_ID/terraform.tfstate" -backend-config="region=ap-south-1" 
            echo ----------------Doing Terraform apply----------------
            terraform apply -var="account_id=$ACCOUNT_ID" --auto-approve
            echo ----------------terraform apply completed on `date`-----------------
            touch Output/scan-$ACCOUNT_ID-done
          fi
        done
    
  post_build:
    commands:
      - echo "Completed Terraform loop for all accounts"
      - ls -lh Output/

artifacts:
  files:
    - 'Main_infra/Output/*'
     